### ISSUE TITLE
Latest build only rendering one font

### ISSUE THREAD

**Issue by neeasade** [krypt-n/bar#11] opened 2015-06-03 18:56 UTC
Default amount of fonts allowed is 5, correct? saw that it was set to that in source. If I have my font set as "Dejavu Sans-8,FontAwesome-8", only the Dejavu text renders, and if I set my font as "FontAwesome-8", the icons render fine( though no text of course ). This is as of a pull of the lemonbar-xft-git aur package today.

**Comment by krypt-n** [comment] 2015-06-03 19:11
Duplicate of #10 
Please use

```
-f "Dejavu Sans-8" -f "FontAwesome-8"
```

I know this is an unannounced breaking change, but I wanted to stay up to date with lemonboy's version

**Closed as completed by krypt-n** 2015-06-03 19:11 UTC

**Comment by neeasade** [comment] 2015-06-03 19:14
Woops, had only glanced through the open issues, alright thanks.
